language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: cd tests/phpunit && ../../vendor/bin/phpunit --testdox